session:
  dynvars:
    username: random_str_12
  snippets:
    - hit_landing_page
    - register_user_and_store_activation_url
    - activate_account
    - login_using_dynvars
    - about_you
    - create_lpa_type
    - push_create_donor_button
    - fill_add_donor_form
    - get_draft_lpa