session:
  dynvars:
    username: random_str_12
  snippets:
    # register user and login
    - hit_landing_page
    - get_user_register
    - post_user_register
    - activate_account
    - get_user_login
    - login_using_dynvars
    - get_about_you
    - post_about_you

    # create LPA
    - get_create_lpa_type
    - post_create_lpa_type

    # create donor
    - get_create_add_donor
    - get_create_add_donor
    - get_postcode_lookup
    - get_address_lookup
    - post_create_add_donor
    - post_create_add_donor
    - get_create_donor
    - get_create_donor
    - get_create_when_to_use
    - post_create_when_to_use

    # create attorneys
    - get_create_attorneys
    - get_create_add_attorney
    - get_postcode_lookup
    - get_address_lookup
    - post_create_add_attorney
    - get_create_attorneys

    # print draft LPA

    - get_pdf_draft_lpa
    # unable to simulate pdf poll without some way of getting UID
    # unable to simulate pdf download without some way of getting UID


# list of requests from live session
#++++++++++++++++++++++++++++++++++
# GET / HTTP/1.1
# GET /user/register HTTP/1.1
# POST /user/register HTTP/1.1
# GET /activate/6ccb5c1114d1d423c1a98d1189a3ecab HTTP/1.1
# GET /user/login HTTP/1.1
# POST /user/login HTTP/1.1
# GET /user/about-you HTTP/1.1
# POST /user/about-you HTTP/1.1
# GET /create/lpa-type HTTP/1.1
# POST /create/lpa-type HTTP/1.1
# GET /create/donor HTTP/1.1
# GET /create/add-donor HTTP/1.1
# GET /user/is-logged-in?_=1397748161961 HTTP/1.1
# GET /postcode/lookup?postcode=SW10+9LB HTTP/1.1
# GET /address/lookup?addressid=23911113 HTTP/1.1
# POST /create/add-donor HTTP/1.1
# GET /create/donor HTTP/1.1
# GET /create/when-to-use HTTP/1.1
# POST /create/when-to-use HTTP/1.1
# GET /create/attorneys HTTP/1.1
# GET /create/add-attorney HTTP/1.1
# GET /user/is-logged-in?_=1397748221311 HTTP/1.1
# GET /postcode/lookup?postcode=SW10+9LB HTTP/1.1
# GET /address/lookup?addressid=23911113 HTTP/1.1
# POST /create/add-attorney HTTP/1.1
# POST /create/add-attorney HTTP/1.1
# GET /pdf/draft/Lasting-Power-of-Attorney-Draft.pdf HTTP/1.1
# GET /pdf/poll/e9043b29dab5810829761c8f583feb52/draft HTTP/1.1
# GET /pdf/download/e9043b29dab5810829761c8f583feb52/draft HTTP/1.1
# GET /create/replacement-attorneys HTTP/1.1
# GET /create/add-replacement-attorney HTTP/1.1
# GET /user/is-logged-in?_=1397748282184 HTTP/1.1
# GET /postcode/lookup?postcode=W4+5RR HTTP/1.1
# GET /address/lookup?addressid=28217290 HTTP/1.1
# POST /create/add-replacement-attorney HTTP/1.1
# GET /create/replacement-attorneys HTTP/1.1
# GET /pdf/draft/Lasting-Power-of-Attorney-Draft.pdf HTTP/1.1
# GET /pdf/poll/60750f82a3e4b17b4a467537b38ad938/draft HTTP/1.1
# GET /pdf/poll/60750f82a3e4b17b4a467537b38ad938/draft HTTP/1.1
# GET /pdf/download/60750f82a3e4b17b4a467537b38ad938/draft HTTP/1.1
# GET /create/certificate-provider HTTP/1.1
# GET /create/add-certificate-provider HTTP/1.1
# GET /user/is-logged-in?_=1397748366936 HTTP/1.1
# GET /postcode/lookup?postcode=SW8+1TB HTTP/1.1
# GET /address/lookup?addressid=23875359 HTTP/1.1
# POST /create/add-certificate-provider HTTP/1.1
# GET /create/certificate-provider HTTP/1.1
# POST /create/certificate-provider HTTP/1.1
# GET /create/people-to-be-told HTTP/1.1
# GET /create/add-notified-person HTTP/1.1
# GET /user/is-logged-in?_=1397748451797 HTTP/1.1
# GET /postcode/lookup?postcode=W8+7PN HTTP/1.1
# GET /address/lookup?addressid=25880236 HTTP/1.1
# POST /create/add-notified-person HTTP/1.1
# GET /create/people-to-be-told HTTP/1.1
# GET /pdf/draft/Lasting-Power-of-Attorney-Draft.pdf HTTP/1.1
# GET /pdf/poll/7077a64e698480f2ddc8f90e14dfa741/draft HTTP/1.1
# GET /pdf/poll/7077a64e698480f2ddc8f90e14dfa741/draft HTTP/1.1
# GET /pdf/download/7077a64e698480f2ddc8f90e14dfa741/draft HTTP/1.1
# GET /create/review HTTP/1.1
# POST /create/review HTTP/1.1
# GET /create/complete HTTP/1.1
# GET /register HTTP/1.1
# GET /register/applicant HTTP/1.1
# POST /register/applicant HTTP/1.1
# GET /register/correspondent HTTP/1.1
# GET /register/signature-dates HTTP/1.1
# POST /register/signature-dates HTTP/1.1
# GET /register/notice-dates HTTP/1.1
# GET /pdf/notification/Lasting-Power-of-Attorney-Notification.pdf HTTP/1.1
# GET /pdf/poll/d0591a9c2d4351078f6f4faea9435eba/notification HTTP/1.1
# GET /pdf/download/d0591a9c2d4351078f6f4faea9435eba/notification HTTP/1.1
# POST /register/notice-dates HTTP/1.1
# GET /register/further-info HTTP/1.1
# POST /register/further-info HTTP/1.1
# GET /register/fees HTTP/1.1
# POST /register/fees HTTP/1.1
# GET /register/payment HTTP/1.1
