session:
  dynvars:
    username: random_str_12
  snippets:
    # register user and login
    # - hit_landing_page
    - hit_landing_page_with_auto_test_key
    - get_user_register
    - post_user_register
    - activate_account
    - get_user_login
    - login_using_dynvars
    - get_about_you
    - post_about_you

    # create LPA
    - get_create_lpa_type
    - post_create_lpa_type

    # create donor
    - get_create_add_donor
    - get_create_add_donor
    - get_postcode_lookup
    - get_address_lookup
    - post_create_add_donor
    - get_create_donor
    - get_create_when_to_use
    - post_create_when_to_use

    # create attorneys
    - get_create_attorneys
    - get_create_add_attorney
    - get_postcode_lookup
    - get_address_lookup
    - post_create_add_attorney
    - get_create_attorneys

    # print draft LPA & add replacement attorney

    - get_pdf_draft_lpa
    - get_create_replacement_attorney
    - get_postcode_lookup
    - get_address_lookup
    - post_create_replacement_attorneys
    - get_create_replacement_attorney
    - get_pdf_draft_lpa

    # add certificate provider

    - get_create_certificate_provider
    - get_create_add_certificate_provider
    - get_postcode_lookup
    - get_address_lookup
    - post_create_add_certificate_provider
    - get_create_certificate_provider
    - post_create_certificate_provider

    # add people to be told
    - get_create_people_to_be_told
    - get_create_add_notified_person
    - get_postcode_lookup
    - get_address_lookup
    - post_create_add_notified_person
    - get_create_people_to_be_told
    - get_pdf_draft_lpa

    # review and complete
    - get_create_review
    - post_create_review
    - get_create_complete
    - get_register_applicant
    - post_register_applicant
    - get_register_notice_dates
    - get_pdf_draft_lpa
    - post_register_notice_dates
    - get_register_further_info
    - post_register_further_info
    - get_register_fees


