match:
  when: match                     # match or nomatch
  source: all                     # all (header + body) or body
  do: dump                        # continue | abort | log | dump | loop (requires sleep_loop and max_loop)
  pattern: "HTTP/1.1 (200|302)"

