request:
  name: POST login as advocate
  url: "/users/sign_in"
  http_method: POST   
  params:
    utf8: "✓"
    # authenticity_token: "%%_csrf_token%%"
    user:
      email: "advocate@example.com"
      password: "liverbird"
      