arrivalphases:
  - name: "Phase 1: 1 customer every second "
    sequence: 1
    duration: 5
    duration_unit: minute
    arrival_interval: 1
    arrival_interval_unit: second

  - name: "Phase 2: 2 customers per second"
    sequence: 2
    duration: 5
    duration_unit: minute
    arrival_interval: 0.5
    arrival_interval_unit: second

  - name: "Phase 3: 4 customers per second"
    sequence: 3
    duration: 5
    duration_unit: minute
    arrival_interval: .025
    arrival_interval_unit: second

  - name: "Phase 4: 8 customers per second"
    sequence: 4
    duration: 5
    duration_unit: minute
    arrival_interval: .0125
    arrival_interval_unit: second

  - name: "Phase 5: 16 customers per second"
    sequence: 5
    duration: 5
    duration_unit: minute
    arrival_interval: 0.0625
    arrival_interval_unit: second

  - name: "Phase 6: 32 customers per seconds"
    sequence: 6
    duration: 5
    duration_unit: minute
    arrival_interval: 0.003125
    arrival_interval_unit: second

  - name: "Phase 7: 64 customers per second"
    sequence: 7
    duration: 5
    duration_unit: minute
    arrival_interval: 0.015625
    arrival_interval_unit: second

  - name: "Phase 8: 128 customers per second"
    sequence: 8
    duration: 5
    duration_unit: minute
    arrival_interval: 0.0078125
    arrival_interval_unit: second