---
request:
  name: 
  url: "/submission"
  http_method: POST
  params:
    utf8: "✓"
    claim:
      :property:
        :street: |-
          Mucho Gracias Road
          London
        :postcode: SW1H 9AJ
        :house: 'Yes'
      :javascript:
        :number_of_claimants: '2'
        :claimant_two_same_address: 'No'
        :any_legal_costs: 'Yes'
        :separate_correspondence_address: 'Yes'
        :other_contact_details: 'Yes'
        :add_reference_number: 'Yes'
        :number_of_defendants: '1'
        :defendant_one_living_in_property: 'No'
        :defendent_two_living_in_property: 
      :claimant_one:
        :title: Mr
        :full_name: John Smith
        :street: |-
          2 Brown St
          Cwmbran
        :postcode: SW1W 0LU
      :claimant_two:
        :title: Ms
        :full_name: Jane Smith
        :street: |-
          7 Main Street
          Alfreton
        :postcode: SW1W 0LU
      :legal_cost:
        :legal_costs: '123.34'
      :claimant_contact:
        :title: Mr
        :full_name: Jim Brown
        :company_name: 
        :street: |-
          3 Smith Street
          Winsum
        :postcode: SW1W 0LU
        :email: jim@example.com
        :phone: 020 000 000
        :fax: 020 000 000
        :dx_number: DX 123
      :reference_number:
        :reference_number: my-ref-123
      :defendant_one:
        :title: Mr
        :full_name: John Kapur
        :street: |-
          Endof Road
          London
        :postcode: SW1X 2PT
      :defendant_two:
        :title: 
        :full_name: 
        :street: 
        :postcode: 
      :tenancy:
        :tenancy_type: Demoted
        :assured_shorthold_tenancy_type: 
        :original_assured_shorthold_tenancy_agreement_date(1i): ''
        :original_assured_shorthold_tenancy_agreement_date(2i): ''
        :original_assured_shorthold_tenancy_agreement_date(3i): ''
        :start_date(1i): ''
        :start_date(2i): ''
        :start_date(3i): ''
        :latest_agreement_date(1i): ''
        :latest_agreement_date(2i): ''
        :latest_agreement_date(3i): ''
        :agreement_reissued_for_same_property: 
        :agreement_reissued_for_same_landlord_and_tenant: 
        :assured_shorthold_tenancy_notice_served_by: 
        :assured_shorthold_tenancy_notice_served_date(1i): ''
        :assured_shorthold_tenancy_notice_served_date(2i): ''
        :assured_shorthold_tenancy_notice_served_date(3i): ''
        :demotion_order_date(1i): '2010'
        :demotion_order_date(2i): '01'
        :demotion_order_date(3i): '01'
        :demotion_order_court: Brighton County Court
        :previous_tenancy_type: assured
      :notice:
        :served_by_name: Somebody
        :served_method: In person
        :date_served(1i): '2014'
        :date_served(2i): '02'
        :date_served(3i): '02'
        :expiry_date(1i): '2014'
        :expiry_date(2i): '02'
        :expiry_date(3i): '02'
      :license:
        :multiple_occupation: 'Yes'
        :issued_under_act_part: Part2
        :issued_by: Local LA
        :issued_date(1i): '2014'
        :issued_date(2i): '02'
        :issued_date(3i): '02'
      :deposit:
        :received: 'Yes'
        :information_given_date(1i): ''
        :information_given_date(2i): ''
        :information_given_date(3i): ''
        :ref_number: X1,234
        :as_money: 'Yes'
        :as_property: 'Yes'
      :order:
        :possession: 'Yes'
        :cost: 'Yes'
      :possession:
        :hearing: 'Yes'
