---
request:
  name: 
  url: "/submission"
  http_method: POST
  params:
    utf8: "✓"
    claim:
      :property:
        :street: |-
          94 East St
          Bristol
        :postcode: BS3 4EY
        :house: 'No'
      :javascript:
        :number_of_claimants: '1'
        :claimant_two_same_address: 
        :any_legal_costs: 'No'
        :separate_correspondence_address: 'Yes'
        :other_contact_details: 'Yes'
        :add_reference_number: 'No'
        :number_of_defendants: '1'
        :defendant_one_living_in_property: 'Yes'
        :defendent_two_living_in_property: 
      :claimant_one:
        :title: Mr
        :full_name: Jay Schneider
        :street: |-
          26 Heath St
          London
        :postcode: NW3 6TE
      :claimant_two:
        :title: 
        :full_name: 
        :street: 
        :postcode: 
      :legal_cost:
        :legal_costs: 
      :claimant_contact:
        :title: Mr
        :full_name: Jay Schneider
        :company_name: Schneider & Sons
        :street: |-
          PO Box 1655, 9 Russell Square
          London
        :postcode: WC1B 5EQ
        :email: jayschneider@gmail.com
        :phone: '7985473222'
        :fax: 
        :dx_number: 
      :reference_number:
        :reference_number: 
      :defendant_one:
        :title: Mr
        :full_name: Andre Drake
        :street: 
        :postcode: 
      :defendant_two:
        :title: 
        :full_name: 
        :street: 
        :postcode: 
      :tenancy:
        :tenancy_type: Assured
        :assured_shorthold_tenancy_type: one
        :original_assured_shorthold_tenancy_agreement_date: 
        :start_date: '1997-02-27'
        :latest_agreement_date: 
        :agreement_reissued_for_same_property: 
        :agreement_reissued_for_same_landlord_and_tenant: 
        :assured_shorthold_tenancy_notice_served_by: Jay Schneider
        :assured_shorthold_tenancy_notice_served_date: '2010-05-24'
        :demotion_order_date: 
        :demotion_order_court: 
        :previous_tenancy_type: 
      :notice:
        :served_by_name: Jay Schneider
        :served_method: By post
        :date_served: '2014-01-04'
        :expiry_date: '2014-03-04'
      :license:
        :multiple_occupation: 'Yes'
        :issued_under_act_part: Part2
        :issued_by: Bristol City Council
        :issued_date: '2010-06-15'
      :deposit:
        :received: 'Yes'
        :information_given_date: '2010-05-25'
        :ref_number: aCpRBZaWPz
        :as_money: 'Yes'
        :as_property: 'No'
      :order:
        :possession: 'Yes'
        :cost: 'No'
      :possession:
        :hearing: 'Yes'
