---
request:
  name: 
  url: "/submission"
  http_method: POST
  params:
    utf8: "✓"
    claim:
      :property:
        :street: |-
          64 Baxtergate
          Whitby
        :postcode: YO21 1BL
        :house: 'Yes'
      :javascript:
        :number_of_claimants: '1'
        :claimant_two_same_address: 
        :any_legal_costs: 'No'
        :separate_correspondence_address: 'No'
        :other_contact_details: 'Yes'
        :add_reference_number: 'No'
        :number_of_defendants: '1'
        :defendant_one_living_in_property: 'Yes'
        :defendent_two_living_in_property: 
      :claimant_one:
        :title: Miss
        :full_name: Sarah Rogers
        :street: |-
          7 Byland Rd
          Whitby
        :postcode: YO21 1JH
      :claimant_two:
        :title: 
        :full_name: 
        :street: 
        :postcode: 
      :legal_cost:
        :legal_costs: 
      :claimant_contact:
        :title: 
        :full_name: 
        :company_name: 
        :street: 
        :postcode: 
        :email: serogers@yahoo.co.uk
        :phone: '7456389234'
        :fax: 
        :dx_number: 
      :reference_number:
        :reference_number: 
      :defendant_one:
        :title: Mr
        :full_name: Mark Davis
        :street: 
        :postcode: 
      :defendant_two:
        :title: 
        :full_name: 
        :street: 
        :postcode: 
      :tenancy:
        :tenancy_type: Assured
        :assured_shorthold_tenancy_type: multiple
        :original_assured_shorthold_tenancy_agreement_date: '2004-03-12'
        :start_date: 
        :latest_agreement_date: '2012-06-14'
        :agreement_reissued_for_same_property: 'Yes'
        :agreement_reissued_for_same_landlord_and_tenant: 'No'
        :assured_shorthold_tenancy_notice_served_by: 
        :assured_shorthold_tenancy_notice_served_date: 
        :demotion_order_date: 
        :demotion_order_court: 
        :previous_tenancy_type: 
      :notice:
        :served_by_name: Royal Mail
        :served_method: In person
        :date_served: '2013-12-13'
        :expiry_date: '2014-02-13'
      :license:
        :multiple_occupation: 'No'
        :issued_under_act_part: 
        :issued_by: 
        :issued_date: 
      :deposit:
        :received: 'Yes'
        :information_given_date: '2004-03-01'
        :ref_number: dKqeU2rK7s
        :as_money: 'Yes'
        :as_property: 'No'
      :order:
        :possession: 'Yes'
        :cost: 'No'
      :possession:
        :hearing: 'Yes'
