arrivalphases:
  - name: Single User
    sequence: 1
    duration: 6
    duration_unit: second
    max_users: 1
    arrival_rate: 5
    arrival_rate_unit: second


# <arrivalphase phase="1" duration="10" unit="minute">
# 	<users maxnumber="100" arrivalrate="10" unit="second"></users>
# </arrivalphase>    