arrivalphases:
  - name: "Phase 1: Full load at 2 requests per second for 5 mins"
    sequence: 1
    duration: 5
    duration_unit: minute
    arrival_interval: 0.5
    arrival_interval_unit: second

  - name: "Phase 2: Full load at 4 requests per second for 5 mins"
    sequence: 2
    duration: 5
    duration_unit: minute
    arrival_interval: 0.25
    arrival_interval_unit: second

  - name: "Phase 3: Full load at 6 requests per second for 5 mins"
    sequence: 3
    duration: 5
    duration_unit: minute
    arrival_interval: 0.1667
    arrival_interval_unit: second
