arrivalphases:
  - name: "Phase 1: Full load at 50 requests per second for 30 mins"
    sequence: 1
    duration: 5
    duration_unit: minute
    arrival_interval: 0.02
    arrival_interval_unit: second