server_host: test_server_host
base_url: http://ec2-54-72-149-249.eu-west-1.compute.amazonaws.com
maxusers: 15000
server_port: 80
http_version: 1.1
load_profile: minimal
loglevel: debug
dumptraffic: true

user_agents:
  - name: Linux Firefox
    user_agent_string: "Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.7.8) Gecko/20050513 Galeon/1.3.21"
    probability: 80
  - name: Windows Firefox
    user_agent_string: "Mozilla/5.0 (Windows; U; Windows NT 5.2; fr-FR; rv:1.7.8) Gecko/20050511 Firefox/1.0.4"
    probability: 20

