server_host: demo_server_host
base_url: https://staging-adp.dsd.io/
maxusers: 9000
server_port: 443
http_version: 1.1
load_profile: single_user
loglevel: debug
dumptraffic: protocol
default_thinktime: 4
default_matches:
  - abort_unless_success_or_redirect


user_agents:
  - name: Linux Firefox
    user_agent_string: "Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.7.8) Gecko/20050513 Galeon/1.3.21"
    probability: 80
  - name: Windows Firefox
    user_agent_string: "Mozilla/5.0 (Windows; U; Windows NT 5.2; fr-FR; rv:1.7.8) Gecko/20050511 Firefox/1.0.4"
    probability: 20


