request:
  name: Get PDF of Draft LPA
  thinktime: 2
  url: '/pdf/draft/Lasting-Power-of-Attorney-Draft.pdf'
  http_method: GET
 



# <request>
#     <match do="loop" sleep_loop="5" max_loop="600" when="match">(.*)Please wait while we are generating your document(.*)</match>
#   	<http url='/pdf/draft/Lasting-Power-of-Attorney-Draft.pdf' version='1.1' method='GET'></http>
#   </request>